const ImageMap = {
  'cakeBg': require('../images/cakeBg.jpg'),
  'coffeeBean1': require('../images/coffeeBean1.jpg'),
  'coffeeBg': require('../images/coffeeBg.jpg'),
  'coffeeBg1': require('../images/coffeeBg1.jpg'),
  'mandalaBakery': require('../images/mandalaBakery.jpg'),
  'pineapple': require('../images/pineappleCake.jpg'),
  'blackForest': require('../images/blackForest.jpg'),
  'whiteForest': require('../images/whiteForest.jpg'),
  'chocolate': require('../images/chocoCake.jpeg'),
  'strawberry': require('../images/strawberryCake.jpg'),
  'vanilla': require('../images/vanillaCake.jpg'),
  'mocha': require('../images/mochaCake.jpg'),
  'blueberry': require('../images/blueberryCake.png'),
  'blueberryCheese': require('../images/blueberryCheeseCake.jpg'),
  'chocolateTruffle': require('../images/chocoTruffleCake.jpg'),
  'sugarLess': require('../images/sugarlessCake.jpg'),
  'iceCream': require('../images/iceCreamCake.png'),
  'cookie': require('../images/cookie.png'),
  'peanutButterCookie': require('../images/peanutButterCookie.png'),
  'cashewNutCookie': require('../images/cashewNut.png'),
  'chocoCookie': require('../images/chocoCookie.png'),
  'whiteBread': require('../images/whiteBread.jpg'),
  'brownBread': require('../images/brownBread.jpg'),
  'multiGrainBread': require('../images/multigrainBread.jpg'),
  'milletBread': require('../images/milletBread.jpg'),
  'wholeWheatBread': require('../images/wholeWheatBread.jpg'),
  'oatMealBread': require('../images/oatmealBread.jpg'),
  'frenchBread': require('../images/frenchBread.jpg'),
  'farmersLoaf': require('../images/farmersLoaf.jpg'),
  'croissantPlainBread': require('../images/croissantPlainBread.jpg'),
  'croissantChocoBread': require('../images/croissantChocolateBread.jpg'),
};

export default ImageMap;
