const ImageMap = {
  'cakeBg': require('../images/cakeBg.jpg'),
  'coffeeBean1': require('../images/coffeeBean1.jpg'),
  'coffeeBg': require('../images/coffeeBg.jpg'),
  'coffeeBg1': require('../images/coffeeBg1.jpg'),
  'mandalaBakery': require('../images/mandalaBakery.jpg'),
  'pineapple': require('../images/pineappleCake.jpg'),
  'blackForest': require('../images/blackForest.jpg'),
  'whiteForest': require('../images/whiteForest.jpg'),
  'chocolate': require('../images/pineappleCake.jpg'),
  'strawberry': require('../images/pineappleCake.jpg'),
  'vanilla': require('../images/pineappleCake.jpg'),
  'mocha': require('../images/pineappleCake.jpg'),
  'blueberry': require('../images/pineappleCake.jpg'),
  'blueberryCheese': require('../images/pineappleCake.jpg'),
  'chocolateTruffle': require('../images/pineappleCake.jpg'),
  'sugarLess': require('../images/pineappleCake.jpg'),
  'iceCream': require('../images/pineappleCake.jpg'),
  'cookie': require('../images/cookie.png'),
  'peanutButterCookie': require('../images/peanutButterCookie.png'),
  'cashewNutCookie': require('../images/cashewNut.png'),
  'chocoCookie': require('../images/chocoCookie.png'),
};

export default ImageMap;
